Jenkinsfile-authoriser-test

This was originally using the tdr function for uploading to S3 but this
is expecting the target directory to be at the top level which it isn't
in this multi project repo. Seeing as it's one line, there's no reason
not to upload this directly.

Upload directly to s3

---

Jenkinsfile-authoriser-deploy

The name of the lambda is tdr-export-api-authoriser-${env}. I've updated the deploy
job so this matches.

Use the correct lambda name.

---

exporter/src/main/scala/uk/gov/nationalarchives/consignmentexport/Main.scala
exporter/src/test/resources/json/get_files_empty.json
exporter/src/test/scala/uk/gov/nationalarchives/consignmentexport/ExternalServiceSpec.scala
exporter/src/test/scala/uk/gov/nationalarchives/consignmentexport/MainSpec.scala

What was happening if you ran this with a non existent consignment was it would try to get the files from the api and the api would return nothing.
This empty list was passed to the s3 downloader which would download nothing.
The program would continue until we had a bagit package with an empty data directory.
Arguably, the API should be rejecting non-existent consignments but for now, this will throw an error if no files are returned by the api.

Throw error if files are missing.

---

exporter/src/main/scala/uk/gov/nationalarchives/consignmentexport/Arguments.scala
exporter/src/main/scala/uk/gov/nationalarchives/consignmentexport/GraphQlApi.scala
exporter/src/main/scala/uk/gov/nationalarchives/consignmentexport/Main.scala
exporter/src/main/scala/uk/gov/nationalarchives/consignmentexport/S3Files.scala
exporter/src/test/scala/uk/gov/nationalarchives/consignmentexport/S3FilesSpec.scala

We were calling mkdir but this has trouble with quotes in file names. If you pass the original path string to a File object and call mkdirs() then it sorts out any character escaping for you.

Replace mkdir with File API

---

authoriser/src/main/scala/uk/gov/nationalarchives/consignmentexport/authoriser/Lambda.scala
exporter/src/main/scala/uk/gov/nationalarchives/consignmentexport/Bagit.scala
exporter/src/main/scala/uk/gov/nationalarchives/consignmentexport/BashCommands.scala
exporter/src/test/scala/uk/gov/nationalarchives/consignmentexport/BashCommandsSpec.scala

`IO.pure` is a way of returning an already-evaluated or hard-coded response. It shouldn't be used for real IO operations, because it is evaluated immediately rather than in the main IO evaluation step.
https://typelevel.org/cats-effect/datatypes/io.html#pure-values--iopure--iounit

Replace IO.pure when running file system and API commands 

---

README.md
exporter/src/main/scala/uk/gov/nationalarchives/consignmentexport/Main.scala
exporter/src/test/resources/application.conf
exporter/src/test/scala/uk/gov/nationalarchives/consignmentexport/ExternalServiceSpec.scala
exporter/src/test/scala/uk/gov/nationalarchives/consignmentexport/MainSpec.scala

Generate a random folder name for each export. This means that if the export task is started twice for the same consignment, the two tasks don't try to read and write the same files in EFS. It also means that we don't have to clean up the files after running the export, because a future export of the same consignment will use a different folder.
This should help to prevent failed exports or corrupted Bagit packages.
Also tests to use /tmp as a temporary directory, rather than src/test/resources, which had a couple of problems:
- It's a relative directory, so it only referenced the expected directory if you ran the tests using `sbt test`. If you used IntelliJ instead, it would create a new src/test/resources directory in the project's root directory instead.
- There are files in …

Run each export in a unique directory

---

Jenkinsfile-testing

We don't need to release the export package if the merge is from the version bump so this filters it out in the same way as we do for the file-metadata.

Don't release if the merge is for a version bump

---

version.sbt

Version numbers out of sync due to Jenkins restart
Manually bump version to force push of new image to ECR

Bump version number

---

project/Dependencies.scala
src/main/scala/uk/gov/nationalarchives/consignmentexport/Main.scala
src/main/scala/uk/gov/nationalarchives/consignmentexport/StepFunction.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/MainSpec.scala

This makes a call to SendTaskHeartbeat every minute. This works by creating a new [cats-effect fiber](https://typelevel.org/cats-effect/docs/2.x/datatypes/fiber) on the call to `runHeartbeat().start` This runs asynchronously to the main thread and then is cancelled at the end just to keep things tidy although it would be killed anyway when the main process exits.
The tests have had to be changed because we're now making to separate calls the step function wiremock endpoint. These are distinguished by the `X-Amz-Target` header so we check for that when we're looking at API calls. I've also added in a test to show that we are calling the heartbeat endpoint.

Send task heartbeat

---

src/main/scala/uk/gov/nationalarchives/consignmentexport/StepFunction.scala

I'm not completely sure why but somewhere between the async thread this
runs in and the async response from the AWS SDK, any errors are ignored
in the main thread.
Calling attempt and then logging based on the value of the either will
log if there are any problems sending the heartbeat.

Add extra logging to the sendHeartbeat method.

---

Dockerfile

Tried upgrading busybox on the openjdk image but it seems to be
on an older version of alpine and there are still vulnerabilities in the
latest version of busybox for that version.
Instead of using the openjdk image, use the
standard alpine image and installed openjdk 15 from the alpine edge
repository.

Use base alpine image with jdk 15 installed

---

src/main/scala/uk/gov/nationalarchives/consignmentexport/Main.scala
src/main/scala/uk/gov/nationalarchives/consignmentexport/StepFunction.scala
src/test/resources/json/publish_judgment_success_request_body.json
src/test/resources/json/publish_success_request_body.json
src/test/scala/uk/gov/nationalarchives/consignmentexport/MainSpec.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/StepFunctionSpec.scala

For notifying transform engine that a package is ready require the 'consignment type' to select the correct s3 bucket

Add 'consignment type' value to output message

---

src/main/scala/uk/gov/nationalarchives/consignmentexport/S3Files.scala

Export for consignments with a large number of files are failing
Appears to be an issue with downloading the files from s3
Temporarily add a sleep between downloading each file to confirm this is what is causing the failure

Temporarily add sleep for downloading files

---

src/main/scala/uk/gov/nationalarchives/consignmentexport/S3Files.scala

Using IO.sleep maybe causing a shut down issue with the JVM for export

Use thread sleep to even out download connections

---

src/main/resources/application.conf
src/main/scala/uk/gov/nationalarchives/consignmentexport/Config.scala
src/main/scala/uk/gov/nationalarchives/consignmentexport/Main.scala
src/main/scala/uk/gov/nationalarchives/consignmentexport/S3Files.scala
src/test/resources/application.conf
src/test/scala/uk/gov/nationalarchives/consignmentexport/GraphQlApiSpec.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/KeycloakClientSpec.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/S3FilesSpec.scala

Trying to download all the files for a large consignments uses up all the s3 connections causing the download to fail
Batching with a pause even outs the burst of request to s3. Pausing on batches is also quicker that pausing on each individual file download request

Download files in batches to even out s3 requests

---

project/Dependencies.scala
src/main/resources/application.conf
src/main/scala/uk/gov/nationalarchives/consignmentexport/BagAdditionalFiles.scala
src/main/scala/uk/gov/nationalarchives/consignmentexport/Main.scala
src/main/scala/uk/gov/nationalarchives/consignmentexport/Validator.scala
src/test/resources/json/get_consignment_for_export.json
src/test/scala/uk/gov/nationalarchives/consignmentexport/BagAdditionalFilesSpec.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/ChecksumValidatorSpec.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/ExternalServiceSpec.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/GraphQlApiSpec.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/S3FilesSpec.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/ValidatorSpec.scala

This gets the originalFilePath if present, or empty string if not and adds it to the file-metadata.csv

Changes for redacted files

---

src/main/scala/uk/gov/nationalarchives/consignmentexport/BagAdditionalFiles.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/BagAdditionalFilesSpec.scala

All the file paths in the bagit files are prefixed with data/ but the
original file path for redacted files isn't and it should be. This adds
it in.

Prefix the original file path with /data

---

src/main/scala/uk/gov/nationalarchives/consignmentexport/BagMetadata.scala
src/main/scala/uk/gov/nationalarchives/consignmentexport/GraphQlApi.scala
src/main/scala/uk/gov/nationalarchives/consignmentexport/Main.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/GraphQlApiSpec.scala

The main class is getting quite long and it's about to get longer now
we're driving the metadata csv from the custom metadata query so I've
moved the BagMetadata into a different method.
I've also changed the graphql API to take a config and consignmentId as
arguments to the class. This avoids each method having to declare them
in the arguments.
I've updated the tests to match.

Refactor the export

---

src/main/scala/uk/gov/nationalarchives/consignmentexport/BagAdditionalFiles.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/BagAdditionalFilesSpec.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/ExportSpec.scala

Multi-properties are added to a single column using a '|' delimiter

TDR-2682 Add multi-value properties to export metadata csv

---

src/main/scala/uk/gov/nationalarchives/consignmentexport/BagAdditionalFiles.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/BagAdditionalFilesSpec.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/ExportSpec.scala

So the 'OriginalFilepath' value matches the non redacted version's 'ClientSideOriginalFilepath' value

Add 'data/' prefix to 'OriginalFilepath'

---

src/main/scala/uk/gov/nationalarchives/consignmentexport/S3Files.scala

For some reason the EFS directory wasn't getting deleted after export. I've added some logging and used more traditional recursive function to delete the directory instead of the experimental scala.reflect.io library

TDR-3132 delete efs directory recursively and add logging

---

project/Dependencies.scala
src/main/scala/uk/gov/nationalarchives/consignmentexport/BagAdditionalFiles.scala
src/main/scala/uk/gov/nationalarchives/consignmentexport/Validator.scala
src/test/resources/json/get_consignment_for_export.json
src/test/resources/json/get_consignment_for_export_different_checksum.json
src/test/resources/json/get_consignment_for_export_empty_folders.json
src/test/resources/json/get_consignment_missing_antivirus_metadata.json
src/test/resources/json/get_judgment_consignment_for_export.json
src/test/resources/json/get_judgment_consignment_for_export_different_checksum.json
src/test/resources/json/get_judgment_consignment_missing_antivirus_metadata.json
src/test/scala/uk/gov/nationalarchives/consignmentexport/BagAdditionalFilesSpec.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/ExternalServiceSpec.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/ValidatorSpec.scala

[TDR-3403](https://national-archives.atlassian.net/browse/TDR-3403?atlOrigin=eyJpIjoiMjNkYzY1MTYxY2MxNDYxNjg2MjlhMTEwOTFkN2E4YjAiLCJwIjoiaiJ9)
[TDR-3403]: https://national-archives.atlassian.net/browse/TDR-3403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TDR-3403 Add file extension "mismatch" and "format name" to Bagit export CSV

---

project/Dependencies.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/BagAdditionalFilesSpec.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/ChecksumValidatorSpec.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/ExportSpec.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/ExternalServiceSpec.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/GraphQlApiSpec.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/S3FilesSpec.scala
src/test/scala/uk/gov/nationalarchives/consignmentexport/ValidatorSpec.scala

I've updated the tdr-generated-graphql to the latest version which includes the FileReference & ParentReference. The tests still needs to be written properly but I want to test if the values show up in the bagit file by testing it on intg.

update tdr-generated-graphql version

---

export/src/main/scala/uk/gov/nationalarchives/export/MetadataUtils.scala
export/src/test/scala/uk/gov/nationalarchives/export/MainTest.scala
export/src/test/scala/uk/gov/nationalarchives/export/TestUtils.scala

We need this on the DR2 side. I've cast the date to a string because
we don't need the full level of accuracy and it avoids any timezone
issues.

Add TransferInitiatedDatetime to export metadata.

---

build.sbt
export/src/main/resources/application.conf
export/src/main/scala/uk/gov/nationalarchives/export/Main.scala
export/src/main/scala/uk/gov/nationalarchives/export/PublishUtils.scala
export/src/main/scala/uk/gov/nationalarchives/export/S3Utils.scala
export/src/test/resources/application.conf
export/src/test/scala/uk/gov/nationalarchives/export/PublishUtilsTest.scala
export/src/test/scala/uk/gov/nationalarchives/export/S3UtilsTest.scala
project/Dependencies.scala

I noticed that this was only sending 1000 messages to the SNS topic.
I originally thought that this was some kind of soft limit on the number
of messages so I've grouped them into batches of 500 and added a 1
second wait between them. It will also check for errors and try again if
there are any.
It turned out that this wasn't the problem after all.
The problem is that listObjectsV2 only returns a maximum of 1000 items.
I really should have noticed that. It now recursively fetches
everything.
Given that the error checking and grouping of the SNS send isn't a bad
idea, even though that wasn't actually the issue, I'm going to leave it
in.

Add list objects pagination and SNS error checking.

---

export/src/main/scala/uk/gov/nationalarchives/export/S3Utils.scala

Having object tagging causes permission issues with downstream service when copy from TDR s3 buckets
TDR should be serving up s3 objects clean with any necessary information held in the metadata
Need to specify empty tag set when using 'x-amz-tagging-directive=REPLACE'
See documentation here: https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html#API_CopyObject_RequestParameters

Tdrd nojira strip object tagging
